// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2KxOcgez96RPiCHLM-wsdqzlqp4AXBH0',
    appId: '1:23857096932:web:2d32d3e2c76877125524f1',
    messagingSenderId: '23857096932',
    projectId: 'belajar-f313e',
    authDomain: 'belajar-f313e.firebaseapp.com',
    storageBucket: 'belajar-f313e.firebasestorage.app',
    measurementId: 'G-ZFKRTJSXPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQqse39WXKIkCQiL1eqJ5yaVfiXMbwTCM',
    appId: '1:23857096932:android:4f24a139b60db2625524f1',
    messagingSenderId: '23857096932',
    projectId: 'belajar-f313e',
    storageBucket: 'belajar-f313e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzOKHGpFkGrQUWZgDbxayT9kVHv9mMlrQ',
    appId: '1:23857096932:ios:719105ba1e2395475524f1',
    messagingSenderId: '23857096932',
    projectId: 'belajar-f313e',
    storageBucket: 'belajar-f313e.firebasestorage.app',
    iosClientId:
        '23857096932-s6j3mpqumchnk25pf18a9oeol4aeqtsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzOKHGpFkGrQUWZgDbxayT9kVHv9mMlrQ',
    appId: '1:23857096932:ios:719105ba1e2395475524f1',
    messagingSenderId: '23857096932',
    projectId: 'belajar-f313e',
    storageBucket: 'belajar-f313e.firebasestorage.app',
    iosClientId:
        '23857096932-s6j3mpqumchnk25pf18a9oeol4aeqtsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2KxOcgez96RPiCHLM-wsdqzlqp4AXBH0',
    appId: '1:23857096932:web:34fe459d7397cf405524f1',
    messagingSenderId: '23857096932',
    projectId: 'belajar-f313e',
    authDomain: 'belajar-f313e.firebaseapp.com',
    storageBucket: 'belajar-f313e.firebasestorage.app',
    measurementId: 'G-EFZ3SSWP5Z',
  );
}
